### PR TITLE
Fixed content extraction for apnews.com

### PR DESCRIPTION
**Pull request by abhishekvm**
----
https://www.apnews.com/amp/0290dd1b2048498783f3d7d0ea28a10d

Root Cause:
1. https://www.apnews.com/amp/0290dd1b2048498783f3d7d0ea28a10d:javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
2. After enabling the SSL logs -Djavax.net.debug=ssl:handshake:verbose came to know that the www.apnews.com expects the Server Name Indication during SSL handshake.
3. The snactory has disabled the SSL Hostname Verification by introducing custom verifier de.jetwick.snacktory.HtmlFetcher.NullHostnameVerifier. As a side effect of this, SNI is not set correctly.

Solution:
1. Disabling the NullHostnameVerifier completely may not work for all the sites SSL verification may fail for many sites.
2. Added a check to specify if site requires SNI to be provided in requests. The domain names can be provided from the config.yaml

### CODE REVIEW

**Comment by skyshard** [comment]
Is it not possible to skip hostname verification with SNI enabled? Basically we want to be very accepting of ssl errors to allow extracting misconfigured sites

**Comment by abhishekvm** [comment]
@skyshard By extending default SSLSocketFactory, always enabled SNI by skipping hostname verification. Now, HtmlFetcherIntegrationTest.testDoubleResolve testcase has started failing after with an error handshake alert:  unrecognized_name. Funny part is the same testcase is running well in my laptop.

Is there a provision to trigger a build again ? I wanted to see if this is random failure or genuine issue.

**Comment by abhishekvm** [comment]
@skyshard @andresp99999 Any pointers on test case failure ? I am not able to re produce the failure on my laptop.

**Comment by andresp99999** [comment]
@abhishek-airpr, I tried running the unit tests locally, what I am seeing is that if I run the HtmlFetcherIntegrationTest.testDoubleResolve test by itself it works fine; however if I run all the tests in HtmlFetcherIntegrationTest then it fails. This seems to indicate a side effect in the tests.

This is what I am seeing:

```
vagrant@vagrant-ubuntu-precise-64:~/snacktory$ sbt
Loading /usr/share/sbt/bin/sbt-launch-lib.bash
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0
[info] Loading project definition from /home/vagrant/snacktory/project
[info] Set current project to snacktory-fork (in build file:/home/vagrant/snacktory/)
> test-only de.jetwick.snacktory.HtmlFetcherIntegrationTest -- --tests=.*testDoubleResolve
[info] Test de.jetwick.snacktory.HtmlFetcherIntegrationTest.testYahooMobile ignored
[info] Test de.jetwick.snacktory.HtmlFetcherIntegrationTest.testXml ignored
[info] Test de.jetwick.snacktory.HtmlFetcherIntegrationTest.testWithTitle ignored
[info] Test de.jetwick.snacktory.HtmlFetcherIntegrationTest.testNoException ignored
[info] Test de.jetwick.snacktory.HtmlFetcherIntegrationTest.testEncoding ignored
[info] Passed: Total 6, Failed 0, Errors 0, Passed 1, Skipped 5
[success] Total time: 7 s, completed Jun 5, 2017 6:35:00 PM
> test-only de.jetwick.snacktory.HtmlFetcherIntegrationTest 
2017-06-05 18:35:20,259 [pool-5-thread-1] WARN  de.jetwick.snacktory.HtmlFetcher - getResolvedUrl:https://m.yahoo.com/w/legobpengine/finance/news/stevia-first-corp-stvf-looks-123500390.html?.intl=us&.lang=en-us Error:Server returned HTTP response code: 500 for URL: https://m.yahoo.com/w/legobpengine/finance/news/stevia-first-corp-stvf-looks-123500390.html?.intl=us&.lang=en-us
2017-06-05 18:35:25,191 [pool-5-thread-1] WARN  de.jetwick.snacktory.HtmlFetcher - getResolvedUrl:https://github.com/teleject/Responsive-Web-Design-Artboards Error:handshake alert:  unrecognized_name
2017-06-05 18:35:26,374 [pool-5-thread-1] INFO  de.jetwick.snacktory.utils.Configuration - Loading snacktory config.yml
2017-06-05 18:35:31,909 [pool-5-thread-1] WARN  de.jetwick.snacktory.HtmlFetcher - getResolvedUrl:http://www.cnn.com/some/article Error:http://www.cnn.com/some/article
[error] Test de.jetwick.snacktory.HtmlFetcherIntegrationTest.testDoubleResolve failed: Bitly
[error] Failed: Total 6, Failed 1, Errors 0, Passed 5
[error] Failed tests:
[error] 	de.jetwick.snacktory.HtmlFetcherIntegrationTest
[error] (test:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 17 s, completed Jun 5, 2017 6:35:34 PM
> test-only de.jetwick.snacktory.HtmlFetcherIntegrationTest -- --tests=.*testDoubleResolve
2017-06-05 18:35:44,557 [pool-6-thread-3] WARN  de.jetwick.snacktory.HtmlFetcher - getResolvedUrl:https://github.com/teleject/Responsive-Web-Design-Artboards Error:handshake alert:  unrecognized_name
2017-06-05 18:35:44,608 [pool-6-thread-3] ERROR de.jetwick.snacktory.HtmlFetcher - Exception for URL: http://t.co/eZRKcEYI:java.io.IOException: Invalid Http response
[info] Test de.jetwick.snacktory.HtmlFetcherIntegrationTest.testYahooMobile ignored
[info] Test de.jetwick.snacktory.HtmlFetcherIntegrationTest.testXml ignored
[info] Test de.jetwick.snacktory.HtmlFetcherIntegrationTest.testWithTitle ignored
[info] Test de.jetwick.snacktory.HtmlFetcherIntegrationTest.testNoException ignored
[info] Test de.jetwick.snacktory.HtmlFetcherIntegrationTest.testEncoding ignored
[error] Test de.jetwick.snacktory.HtmlFetcherIntegrationTest.testDoubleResolve failed: 
[error] Failed: Total 6, Failed 1, Errors 0, Passed 0, Skipped 5
[error] Failed tests:
[error] 	de.jetwick.snacktory.HtmlFetcherIntegrationTest
[error] (test:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 3 s, completed Jun 5, 2017 6:35:44 PM
```

I'll try to take a close look this evening.

**Review by skyshard — APPROVED** [review]

**Pull request merged**
